### PR TITLE
added mean-eddy decomposition function to utils

### PR DESCRIPTION
**Pull request by dantecn**

### CODE REVIEW

**Comment by iuryt** [comment]
Should we add this `parallel_client`? Isn't better just give an example on documentation?

**Comment by dantecn** [comment]
> Should we add this `parallel_client`? Isn't better just give an example on documentation?

Is there a way to have the function defined (so we may call it from other functions), but not available to users? Removing it from `__init__` would do the trick?

**Comment by iuryt** [comment]
> > Should we add this `parallel_client`? Isn't better just give an example on documentation?
> 
> Is there a way to have the function defined (so we may call it from other functions), but not available to users? Removing it from `__init__` would do the trick?

Usually, functions like this are defined with underscore in other packages `._parallel_client`

**Comment by dantecn** [comment]
> > > Should we add this `parallel_client`? Isn't better just give an example on documentation?
> > 
> > 
> > Is there a way to have the function defined (so we may call it from other functions), but not available to users? Removing it from `__init__` would do the trick?
> 
> Usually, functions like this are defined with underscore in other packages `._parallel_client`

Should it be an isolated function, like `ls OceanLab`  
      ` dyn.py  eof.py  __init.py__  oa.py  utils.py ._parallel_client`,  
or do I create a `support.py` containing `._parallel client` only to be imported by dyn.py etc?

**Comment by MariaMigl** [comment]
With that approach I believe you can still keep it in the same file(module). However in this case if possible to make it not able to import at all I think it makes more sense than the dunder approach

**Pull request merged**
